name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
env:
  PLUGIN_NAME: obsidian-vscode-editor # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build plugin
        run: |
          pnpm install
          pnpm run build

      # Package the required files into a zip
      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css README.md ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip ${{ env.PLUGIN_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # main.css
          generate_release_notes: true
          draft: true
          files: |
            main.js
            manifest.json
            styles.css
            ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip